services:
  - type: web
    name: service-request-board-api
    runtime: node
    plan: free
    buildCommand: yarn
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
